print'1.13 Exercises'
print'Exercise 1: What is the function of the secondary memory in a computer?'
print'a) Execute all of the computation and logic of the program'
print'b) Retrieve web pages over the Internet'
print'c) Store information for the long term, even beyond a power cycle d) Take input from the user'